### ISSUE TITLE
Alt text on images

### ISSUE THREAD

**Issue by lynn** [j-e-d/NYTdiff#3]
Hey, I think it would be nifty if the bot's images came with [alt text](https://help.twitter.com/en/using-twitter/picture-descriptions) describing the before-and-after for users who can't view images.

It seems you can use [`create_media_metadata`](http://docs.tweepy.org/en/latest/api.html#API.create_media_metadata) after `media_upload` to achieve this. Probably, something like `Before: {old}. After: {new}.` is the least confusing format to provide alt text in. The limit is 1000 characters.

**Comment by j-e-d** [comment]
Thanks for the suggestion, I've had this in mind ar some moment but never got around to do it.

I wasn't sure if I should use your suggested format or html `<ins>` and `<del>` tags? 

Example: 

1. Before: This is the original headline.
    After: This is the modified headline.
2. This is the <del>original</del> <ins>modified</ins> headline.

I guess option 1 is difficult when the text is long and the change isn't big. Option 2 it's similar to the image format but might be difficult to follow for those using screen readers, and I'm not sure if the screen readers handle html those tags.

**Comment by j-e-d** [comment]
I've updated the code that is running the bot to add the suggested format.

Example here: https://twitter.com/nyt_diff/status/1272539309107826693/photo/1
```
<img alt="Before: In New York and Texas, there has been frustration as people flout restrictions related to the virus, which experts say is not going anywhere fast. Parts of Beijing have been locked down to contain a new outbreak. 
After: Beijing officials are scrambling to track cases linked to a sprawling food market. In New York and Texas, frustration is growing as people flout restrictions." draggable="true" src="https://pbs.twimg.com/media/Eaj3waVXYAcg2Za?format=png&amp;name=small" class="css-9pa8cd">
```

Thanks @lynn

**Comment by lynn** [comment]
Awesome!! Thank you! :heart:
