### ISSUE TITLE
Simplify Diff for Substantial Changes

### ISSUE THREAD

**Issue by Sircular** [j-e-d/NYTdiff#6]
For some changes in title and abstract, there are spurious similarities that make the diffs difficult to understand (for example https://twitter.com/nyt_diff/status/1353771665017221120).

Would a pull request that detected if, say, 30% or less of the original text was unchanged and replaced it with "-old-headline- new headline" be accepted?

**Comment by j-e-d** [comment]
Hey, thanks for asking and the suggestion. My fear with that would be that with some long titles and specially with long abstracts the image would be even higher than what they currently are and make them harder to follow. But the main issue I have is that I don't want two different kind of outputs for the bot. Currently the bot has alt-text for the images that was added to address #3, that has the 
> Before: xyz
   After: xyx

format. But I know that most people don't see the alt-text with the default browser configs. Maybe an alternative could be a companion bot that answers to each diff with the text versions of `old` and `new`.

**Comment by Sircular** [comment]
I'm not sure what you mean by "two different kinds of outputs for the bot." Wouldn't it be the same format, but just have the entire old headline removed and the entire new one added?

Also I understand how making the images taller might cut them off in previews, but I'm not sure I understand why that would make it "harder to follow."

I don't mean to be rude or insistent; apologies if I come off that way.

**Comment by j-e-d** [comment]
By "two different kinds of outputs" I mean two styles of diffs, one with the changes inline as we currently have for the cases where most of the original text is unchanged an another with the complete old title and the new title when the texts are very different but still have some word in common. 
I played around with the script using the headline in the link you sent and with the abstract of that same thread to test how they would look:

![image](https://user-images.githubusercontent.com/387669/105850867-0f99da00-5fc1-11eb-9d5b-9aaadfa2c633.png)

![image](https://user-images.githubusercontent.com/387669/105850960-30622f80-5fc1-11eb-85cc-fe1850e7fc2d.png)
